[project]
name = "message-board"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "bleach>=6.2.0",
    "flask>=3.1.2",
    "gel>=3.1.0",
    "python-dotenv>=1.2.1",
    "requests>=2.32.5",
    "resend>=2.19.0",
]
